import { IAirport } from '../app/model/airport.model';

export const MOCK_AIRPORT: IAirport[] = [
  {
    name: 'Chumphon Downtown',
    code: 'CJ1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chumphon Downtown',
    code: 'CJ3',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Gaya Airport',
    code: 'GAY',
    currency: 'INR',
    countryCode: 'IND',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'KOH LIPE',
    code: 'LPR',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Macau International Airport',
    code: 'MFM',
    currency: 'USD',
    countryCode: 'MAC',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'NANJING LUKOU INTERNATIONAL AIRPORT',
    code: 'NKG',
    currency: 'CNY',
    countryCode: 'CHN',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Satun(Pak Bara Pier)',
    code: 'PB1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Satun(Pak Bara Pier)',
    code: 'PB3',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Ranong (Pak Nam pier)',
    code: 'PN1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Ranong (Pak Nam pier)',
    code: 'PN3',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Tungmakam Noi',
    code: 'TM1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Tungmakam Noi',
    code: 'TM3',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'KOH PHA NGAN',
    code: 'TP0',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Koh Phangan Pier',
    code: 'TSP',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'LOMPRAYAH DONSAK PIER',
    code: 'UR3',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Lal Bahadur Shastri Airport',
    code: 'VNS',
    currency: 'INR',
    countryCode: 'IND',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'SUNAN SHUOFANG INTERNATIONAL AIRPORT',
    code: 'WUX',
    currency: 'CNY',
    countryCode: 'CHN',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'YIWU AIRPORT',
    code: 'YIW',
    currency: 'CNY',
    countryCode: 'CHN',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Don Mueang (Bangkok)',
    code: 'DMK',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Suvarnabhumi (Bangkok)',
    code: 'BKK',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Betong (Yala)',
    code: 'BTZ',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Buri Ram',
    code: 'BFV',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chiang Mai',
    code: 'CNX',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chiang Rai',
    code: 'CEI',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chumphon',
    code: 'CJM',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Hat Yai',
    code: 'HDY',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Khon Kaen',
    code: 'KKC',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Krabi',
    code: 'KBV',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Lampang',
    code: 'LPT',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Loei',
    code: 'LOE',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Mae Hong Son',
    code: 'HGN',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Mae Sot',
    code: 'MAQ',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Phanom',
    code: 'KOP',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Ratchasima',
    code: 'NAK',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Si Thammarat',
    code: 'NST',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nan',
    code: 'NNT',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Phitsanulok',
    code: 'PHS',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Phrae',
    code: 'PRH',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Phuket',
    code: 'HKT',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Ranong',
    code: 'UNN',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Roi Et',
    code: 'ROI',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Sakon Nakhon',
    code: 'SNO',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Surat Thani',
    code: 'URT',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Trang',
    code: 'TST',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'U-TAPAO',
    code: 'UTP',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Ubon Ratchathani',
    code: 'UBP',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Udon Thani',
    code: 'UTH',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Hiroshima, Japan',
    code: 'HIJ',
    currency: 'JPY',
    countryCode: 'JPN',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chengdu (Tianfu), China',
    code: 'TFU',
    currency: 'CNY',
    countryCode: 'CHN',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Ho Chi Minh City, Vietnam',
    code: 'SGN',
    currency: 'USD',
    countryCode: 'VNM',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nanning, China',
    code: 'NNG',
    currency: 'CNY',
    countryCode: 'CHN',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Yangon, Myanmar',
    code: 'RGN',
    currency: 'USD',
    countryCode: 'MMR',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Zhengzhou, China',
    code: 'CGO',
    currency: 'CNY',
    countryCode: 'CHN',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Changi, Singapore',
    code: 'SIN',
    currency: 'USD',
    countryCode: 'SGP',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Amnat Charoen',
    code: 'AM1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chiang Rai (Mae Sai)',
    code: 'MI1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chumphon (Pak Nam)',
    code: 'CP1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chumphon (Pathio)',
    code: 'PA1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chumphon (Sai Ri Beach)',
    code: 'SA1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Chumphon (Thung Wua Laen)',
    code: 'TW1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Loei (Chiang Khan)',
    code: 'CK1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Loei (Phu Kradueng)',
    code: 'PK1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Mukdahan',
    code: 'MH1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Phanom',
    code: 'KP1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Phanom (That Phanom)',
    code: 'TN1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Si Thammarat (Khanom)',
    code: 'KN1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Si Thammarat (Kiriwong)',
    code: 'KW1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Si Thammarat (Sichon)',
    code: 'SC1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Si Thammarat (Tha Sala)',
    code: 'TA1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nakhon Si Thammarat (Thung Song)',
    code: 'TS1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Nong Khai',
    code: 'NI1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Pattani via Hat Yai',
    code: 'PT1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Phetchabun (Khao Kho)',
    code: 'KK1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Surat Thani (Donsak-Raja Ferry Pier)',
    code: 'DS1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Surat Thani (Khao Sok)',
    code: 'KS1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Surat Thani (Ratchaprapa Dam)',
    code: 'RP1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Surin',
    code: 'SR1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Trang (Kantang)',
    code: 'KA1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Uttaradit',
    code: 'UD1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Yala via Hat Yai',
    code: 'YL1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Yasothon',
    code: 'YS1',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Koh Lipe',
    code: 'LP0',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Koh Nang Yuan',
    code: 'NY0',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Koh Phangan (Thong Sala Pier)',
    code: 'TS0',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Koh Samui (Nathon Pier)',
    code: 'US0',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Koh Tao',
    code: 'TA0',
    currency: 'THB',
    countryCode: 'THA',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
  {
    name: 'Hyderabad, India',
    code: 'HYD',
    currency: 'INR',
    countryCode: 'IND',
    restrictedOnDeparture: false,
    restrictedOnDestination: false,
  },
];
